steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud functions deploy helloWorld \
      --region=us-central1 \
      --runtime=nodejs18 \
      --trigger-http \
      --allow-unauthenticated \
      --project=satander-gcp1 \
      --service-account=1016928842867-compute@developer.gserviceaccount.com



options:
  logging: CLOUD_LOGGING_ONLY
