steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Fetching secret..."
        SECRET=$(gcloud secrets versions access 1 --secret=dsfsdf)
        echo "SECRET=$SECRET" > /workspace/secret.env

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'functions'
      - 'deploy'
      - 'hello_world'
      - '--runtime'
      - 'python39'
      - '--trigger-http'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'MY_SECRET=$(grep SECRET /workspace/secret.env | cut -d "=" -f 2)'

options:
  logging: CLOUD_LOGGING_ONLY
