steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud functions deploy hello_world \
          --runtime python310 \
          --trigger-http \
          --allow-unauthenticated \
          --project=satander-gcp1 \
          --service-account=1016928842867-compute@developer.gserviceaccount.com

options:
  logging: CLOUD_LOGGING_ONLY
