steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Deploying Cloud Function..."
        gcloud functions deploy hello_world \
          --runtime python39 \
          --trigger-http \
          --allow-unauthenticated \
          --set-env-vars MY_SECRET="$_SECRET_MY_SECRET"
    secretEnv: ['_SECRET_MY_SECRET']

availableSecrets:
  secretManager:
    - versionName: projects/kilo-gcp/secrets/dsfsdf/versions/1
      env: '_SECRET_MY_SECRET'

options:
  logging: CLOUD_LOGGING_ONLY
