steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args: ['-c', 'echo "Deploying Cloud Function..."']
    secretEnv: ['MY_SECRET']

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Deploying Cloud Function with secret..."
        gcloud functions deploy hello_world \
          --runtime python39 \
          --trigger-http \
          --allow-unauthenticated \
          --set-env-vars MY_SECRET="$MY_SECRET"
    secretEnv: ['MY_SECRET']

availableSecrets:
  secretManager:
    - versionName: projects/kilo-gcp/secrets/dsfsdf/versions/1
      env: 'MY_SECRET'

options:
  logging: CLOUD_LOGGING_ONLY
